// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HObuw_0JavPPQ5hc69zWsMcmx3Wxzrg',
    appId: '1:543819470636:web:6ce577941204ec3f8efe89',
    messagingSenderId: '543819470636',
    projectId: 'attendance-app-de676',
    authDomain: 'attendance-app-de676.firebaseapp.com',
    storageBucket: 'attendance-app-de676.appspot.com',
    measurementId: 'G-YXL45NR9R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAouJVNEpAwbBoLFWjOmvfqyWytPiCc8uk',
    appId: '1:543819470636:android:3ee78e86f94650448efe89',
    messagingSenderId: '543819470636',
    projectId: 'attendance-app-de676',
    storageBucket: 'attendance-app-de676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNKVDnI2i6C0tBOm-Plle5Wg4BIoD1dGs',
    appId: '1:543819470636:ios:6789cca8590f884a8efe89',
    messagingSenderId: '543819470636',
    projectId: 'attendance-app-de676',
    storageBucket: 'attendance-app-de676.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNKVDnI2i6C0tBOm-Plle5Wg4BIoD1dGs',
    appId: '1:543819470636:ios:4fee48a909a8a11b8efe89',
    messagingSenderId: '543819470636',
    projectId: 'attendance-app-de676',
    storageBucket: 'attendance-app-de676.appspot.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
